
from ..brain.groq import think
import sys
import json
from rich import print
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
import time
from datetime import datetime

console = Console()

def save_reports(response, logs, indices):
    timestamp = int(time.time())
    incident_file = f"incidents/incident_{timestamp}.json"
    record = {
        "Timestamp": timestamp,
        "Analysis": response,
        "raw_error_snippit": [logs[i] for i in indices]
    }
    with open(incident_file, 'w') as f:
        json.dump(record, f)
    return record

def heimdall(logs):
    if not logs:
        console.print("[red]No logs provided[/red]")
        return {"error": "No logs provided"}

    logs = logs[-50:]
    keywords = ['error', 'critical', 'fatal', 'traceback', 'exception', 'panic', 'warn']
    indices = [i for i, log in enumerate(logs) if any(keyword in log.lower() for keyword in keywords)]

    if not indices:
        return {"error": "No errors found in logs"}

    min_index = min(indices)
    max_index = max(indices)
    aggregated_text = '\n'.join(logs[max(0, min_index-10):min(len(logs), max_index+11)])

    try:
        response = think(aggregated_text)
        response = json.loads(response)
    except json.JSONDecodeError:
        return {"error": "Failed to parse response from AI"}

    if 'title' not in response or 'root_cause' not in response or 'fix' not in response:
        return {"error": "Invalid response from AI"}

    console.status("Generating incident report...")
    table = Table(title="Error Snippets")
    table.add_column("Line Number", style="cyan")
    table.add_column("Error Snippet", style="magenta")
    for index in indices:
        table.add_row(str(index+1), logs[index])

    panel = Panel(
        f"[bold]{response['title']}[/bold]\n"
        f"Root Cause: {response['root_cause']}\n"
        f"Fix: {response['fix']}",
        title="Incident Report",
        subtitle="Generated by Heimdall"
    )

    console.print(panel)
    console.print(table)

    record = save_reports(response, logs, indices)
    return record

if __name__ == "__main__":
    logs = sys.stdin.readlines()
    logs = [log.strip() for log in logs]
    response = heimdall(logs)
    print(json.dumps(response))
